server:
  port: 8808
owl:
  # owl home dir
  home: ${OWL_HOME:owl}
spring:
  datasource:
    # JDBC连接串
    # sqlite仅作为开发环境使用，生产环境下请使用mysql：jdbc:mysql://localhost:3306/owl
    url: jdbc:sqlite:${owl.home}/db/owl_db.sqlite
    # JDBC用户
    username:
    # JDBC密码
    password:
    # JDBC使用Hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置信息
    hikari:
      pool-name: OwlDatasourePool
      # 自动提交从池中返回的连接
      auto-commit: true
      # 客户端等待连接池连接的最大毫秒数
      connection-timeout: 30000
      # 连接允许在池中闲置的最长时间
      idle-timeout: 30000
      # 池中连接最长生命周期
      max-lifetime: 1800000
      # 连接池中维护的最小空闲连接数
      minimum-idle: 1
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 1
      # 用来检测连接是否有效，要求是一个查询语句
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    ignore-missing-migrations: true
    ignore-ignored-migrations: true
    ignore-pending-migrations: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    baseline-description: Baseline
    table: _migration
    locations: classpath:db/migration/sqlite
    placeholder-replacement: false